### ISSUE TITLE
What's the jvm's unique value proposition when compared to jenv and jabba?

### ISSUE THREAD

**Issue by inancgumus** [caarlos0/jvm#53]
- [jenv](https://github.com/gcuisinier/jenv)
- [jabba](https://github.com/shyiko/jabba)

**Comment by caarlos0** [comment]
I think the main differences is that jvm doesn't install any jdks and relies on some defaults, which seems to me that other do not.

I think one of those also supports custom JAVA_OPTS for each jdk and etc, which jvm do not.

jvm can also parse the version from pom and gradle files, which I don't know if other do.

Besides that, I don't think there is much difference.

**Comment by inancgumus** [comment]
@caarlos0 Thanks, better to add this in Wiki or to README.md.
